#!/bin/bash

function docker_api {
    local host
    local path=${1:-/}
    local method=${2:-GET}
    local data=${3:-}
    local curl_opts=(-s)

    if [ "$method" = 'POST' ]; then
        curl_opts+=(-d "$data")
        if [ -n "$data" ]; then
            curl_opts+=(-H 'Content-Type: application/json')
        fi
    elif [ -n "$data" ]; then
        curl_opts+=(--get)
        curl_opts+=(--data-urlencode "$data")
    fi
    if [ -z "$DOCKER_HOST" ];then
        echo "Error DOCKER_HOST variable not set" >&2
        return 1
    fi
    if [ -n "${DOCKER_HOST#unix://}" ]; then
        curl_opts+=(--unix-socket ${DOCKER_HOST#unix://})
        host='http://localhost'
    else
        host="http://${DOCKER_HOST#*://}"
    fi
    curl "${curl_opts[@]}" ${host}$path
}

function docker_kill {
    local id="${1?missing id}"
    local signal="${2?missing signal}"
    docker_api "/containers/$id/kill?signal=$signal" "POST"
}

containers=$(docker_api "/containers/json" "GET" 'filters={"label": ["'$1'"]}' | jq -r '[.[] | .Id] | join(" ")')
if [ -z "${containers:-}" ]; then
    echo "Error: can't get containers for label '$1'" >&2
    exit 1
fi

for cid in ${containers}; do
    echo "Sending SIGHUP to $cid..."
    docker_kill "$cid" SIGHUP
done
